In [1]:
# =============================================================================
# Standard Library
# =============================================================================
import re
import string
from nltk.corpus import stopwords

# =============================================================================
# Data Processing
# =============================================================================
import pandas as pd
import numpy as np

In [2]:
# =============================================================================
# Load the processed dataset
# =============================================================================
dataset = pd.read_csv("cleaned_dataset.csv")

In [3]:
# Semantic Text Preprocessing
# =============================================================================
# Clean text for semantic embedding models
# =============================================================================

def clean_text_semantic(text):
    """
    Clean text while preserving semantic meaning.
    """

    # Convert to string
    text = str(text)

    # Convert text to lowercase
    text = text.lower()

    # Remove HTML tags
    text = re.sub(r"<.*?>", " ", text)

    # Remove URLs
    text = re.sub(r"http\S+|www\S+", " ", text)

    # Remove email addresses
    text = re.sub(r"\S+@\S+", " ", text)

    # Remove extra whitespace
    text = re.sub(r"\s+", " ", text)

    # Remove leading and trailing spaces
    text = text.strip()

    return text


# =============================================================================
# Create semantic text for embedding generation
# =============================================================================

dataset["semantic_text"] = (
    "Question: "
    + dataset["QuestionText"].apply(clean_text_semantic)
    + "\n\nAnswer: "
    + dataset["AnswerText"].apply(clean_text_semantic))

# Preview semantic text
dataset[["semantic_text"]].head()

                                       semantic_text
0  Question: will they fit 2013 f350 dually\n\nAn...
1  Question: will they fit 2013 f350 dually\n\nAn...
2  Question: will they fit 2013 f350 dually\n\nAn...
3  Question: will they fit 2013 f350 dually\n\nAn...
4  Question: will they fit 2013 f350 dually\n\nAn...

In [4]:
# Lexical (BM25) Text Preprocessing
# =============================================================================
# Clean text for BM25 lexical retrieval
# =============================================================================

def clean_text_bm25(text):
    """
    Clean text for lexical search.
    """

    # Convert to string
    text = str(text)

    # Convert text to lowercase
    text = text.lower()

    # Remove HTML tags
    text = re.sub(r"<.*?>", " ", text)

    # Remove URLs
    text = re.sub(r"http\S+|www\S+", " ", text)

    # Remove email addresses
    text = re.sub(r"\S+@\S+", " ", text)

    # Remove punctuation
    text = text.translate(
        str.maketrans("", "", string.punctuation)
    )

    # Remove extra whitespace
    text = re.sub(r"\s+", " ", text)

    # Remove leading and trailing spaces
    text = text.strip()

    return text

In [5]:
# BM25 Tokenization
# =============================================================================
# Load English stopwords
# =============================================================================

stop_words = set(stopwords.words("english"))


# =============================================================================
# Prepare text for BM25 indexing
# =============================================================================

def preprocess_bm25(text):
    """
    Clean, tokenize, and remove stopwords for BM25.
    """

    # Apply lexical cleaning
    text = clean_text_bm25(text)

    # Split into tokens
    tokens = text.split()

    # Remove stopwords
    tokens = [
        token
        for token in tokens
        if token not in stop_words]

    # Join tokens into a single string
    return " ".join(tokens)

In [6]:
# Create BM25 Text
# =============================================================================
# Create lexical text for BM25 retrieval
# =============================================================================

dataset["lexical_text"] = (
    dataset["QuestionText"].apply(preprocess_bm25)
    + " "
    + dataset["AnswerText"].apply(preprocess_bm25))

# Preview lexical text
dataset[["lexical_text"]].head()

                                        lexical_text
0  fit 2013 f350 dually custom mounting theres th...
1  fit 2013 f350 dually need drill another hole m...
2  fit 2013 f350 dually since installed dont thin...
3  fit 2013 f350 dually 1 pair rear flaps mountin...
4  fit 2013 f350 dually didnt buy bought soninlaw...

In [7]:
# =============================================================================
# Compare original and processed text
# =============================================================================

sample = 0

print("Original Question")
print(dataset.loc[sample, "QuestionText"])

print("\nOriginal Answer")
print(dataset.loc[sample, "AnswerText"])

print("\nSemantic Text")
print(dataset.loc[sample, "semantic_text"])

print("\nLexical Text")
print(dataset.loc[sample, "lexical_text"])

Original Question
will they fit 2013 f350 dually

Original Answer
It's all custom mounting, where there's a will there's a way, don't see why not, figure 15minutes per mud flap, there isn't any hardware included just the stamped sheet metal pieces

Semantic Text
Question: will they fit 2013 f350 dually

Answer: it's all custom mounting, where there's a will there's a way, don't see why not, figure 15minutes per mud flap, there isn't any hardware included just the stamped sheet metal pieces

Lexical Text
fit 2013 f350 dually custom mounting theres theres way dont see figure 15minutes per mud flap isnt hardware included stamped sheet metal pieces

In [8]:
# =============================================================================
# Save the preprocessed dataset
# =============================================================================
dataset.to_csv("preprocessed_dataset.csv", index=False)

print("Preprocessed dataset saved successfully.")

Preprocessed dataset saved successfully.